version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
  blockchain:
    container_name: blockchain
    image: arianeetech/arianeejs-blockchain
    entrypoint: ["node", "/app/ganache-core.docker.cli.js", "--deterministic", "-g", "1", "-e", "100", "--gasLimit", "8000000", "--db", "/usr/src/app"]
    ports:
      - 8545:8545
  privacy-gateway:
    container_name: rpc
    build:
      context: "https://${GITHUBTOKEN}@github.com/Arianee/docker-rpc-server.git#master"
    links:
      - mongo
    ports:
      - 3002:3000
    environment:
      - MONGODB_ADDON_URI=mongodb://mongodb:27017/mydatabase
      - NODE_ENV:development
      - PORT=3000
  faucet:
    container_name: faucet
    build:
      context: "https://${GITHUBTOKEN}@github.com/Arianee/arianee-faucet.git#clever-cloud"
    ports:
      - 3000:3000

