/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Arianee Certificate i18n
 */
export type $Schema = string;
/**
 * Product Name
 */
export type Name = string;
/**
 * Product Sku
 */
export type SKU = string;
/**
 * Product GTIN
 */
export type GTIN = string;
/**
 * Product Internal Brand ID
 */
export type BrandInternalID = string;
export type Category = Apparel | Accessory;
/**
 * Apparel
 */
export type Apparel = "apparel";
/**
 * Accessory
 */
export type Accessory = "accessory";
export type SubCategory = Shirt | Dress;
/**
 * Shirt
 */
export type Shirt = "shirt";
/**
 * Dress
 */
export type Dress = "dress";
export type Intended = WomenS | MenS | AdultGenderNeutral;
/**
 * Women's
 */
export type WomenS = "womens";
/**
 * Men's
 */
export type MenS = "mens";
/**
 * Adult Gender Neutral
 */
export type AdultGenderNeutral = "neutral";
export type Type = SerialNumber | CaseNumber | MovementNumber;
/**
 * Serial Number
 */
export type SerialNumber = "serialnumber";
/**
 * Case Number
 */
export type CaseNumber = "casenumber";
/**
 * Movement Number
 */
export type MovementNumber = "movementnumber";
export type Value = string;
export type SerialNumber1 = {
    type?: Type;
    value?: Value;
    [k: string]: any;
}[];
/**
 * Sub Brand
 */
export type SubBrand = string;
/**
 * Product model
 */
export type Model = string;
export type Language = French | EnglishUS | ChineseTraditional | ChineseSimplified;
/**
 * French
 */
export type French = "fr-FR";
/**
 * English (US)
 */
export type EnglishUS = "en-US";
/**
 * Chinese (traditional)
 */
export type ChineseTraditional = "zh-TW";
/**
 * Chinese (simplified)
 */
export type ChineseSimplified = "zh-CN";
/**
 * Product Description
 */
export type Description = string;
export type Type1 = Servicing | Recycling | Other;
/**
 * Servicing
 */
export type Servicing = "service";
/**
 * Recycling
 */
export type Recycling = "recycling";
/**
 * other
 */
export type Other = "other";
export type Title = string;
export type Content = string;
export type OrderNumber = number;
export type DescriptionMore = {
    type?: Type1;
    title?: Title;
    content?: Content;
    order?: OrderNumber;
    [k: string]: any;
}[];
export type Type2 = WebsiteMain | Eshop | Other1;
/**
 * Website (main)
 */
export type WebsiteMain = "website";
/**
 * Eshop
 */
export type Eshop = "eshop";
/**
 * other
 */
export type Other1 = "other";
export type Title1 = string;
export type Url = string;
export type OrderNumber1 = number;
export type ExternalContents = {
    type?: Type2;
    title?: Title1;
    url?: Url;
    order?: OrderNumber1;
    [k: string]: any;
}[];
export type Language1 = French1 | EnglishUS1 | ChineseTraditional1 | ChineseSimplified1;
/**
 * French
 */
export type French1 = "fr-FR";
/**
 * English (US)
 */
export type EnglishUS1 = "en-US";
/**
 * Chinese (traditional)
 */
export type ChineseTraditional1 = "zh-TW";
/**
 * Chinese (simplified)
 */
export type ChineseSimplified1 = "zh-CN";
export type Description1 = string;
export type Type3 = Servicing1 | Recycling1 | Other2;
/**
 * Servicing
 */
export type Servicing1 = "service";
/**
 * Recycling
 */
export type Recycling1 = "recycling";
/**
 * other
 */
export type Other2 = "other";
export type Title2 = string;
export type Content1 = string;
export type OrderNumber2 = number;
export type DescriptionMore1 = {
    type?: Type3;
    title?: Title2;
    content?: Content1;
    order?: OrderNumber2;
    [k: string]: any;
}[];
export type Type4 = WebsiteMain1 | Eshop1 | Other3;
/**
 * Website (main)
 */
export type WebsiteMain1 = "website";
/**
 * Eshop
 */
export type Eshop1 = "eshop";
/**
 * other
 */
export type Other3 = "other";
export type Title3 = string;
export type Url1 = string;
export type OrderNumber3 = number;
export type ExternalContents1 = {
    type?: Type4;
    title?: Title3;
    url?: Url1;
    order?: OrderNumber3;
    [k: string]: any;
}[];
export type OtherLanguagesDescriptionExternalContents = {
    language?: Language1;
    description?: Description1;
    subDescription?: DescriptionMore1;
    externalContents?: ExternalContents1;
    [k: string]: any;
}[];
/**
 * Manufacturers suggested retail price (number)
 */
export type MSRP = string;
/**
 * Currency
 */
export type Currency = USDollar | Euro | Pound;
/**
 * US Dollar
 */
export type USDollar = "USD";
/**
 * Euro
 */
export type Euro = "EUR";
/**
 * Pound
 */
export type Pound = "GBP";
/**
 * Country of Intended Original Sale (ISO 3166 alpha-3)
 */
export type CountryMsrp = string;
export type ManufacturersSuggestedRetailPrice = {
    msrp?: MSRP;
    currency?: Currency;
    msrpCountry?: CountryMsrp;
    [k: string]: any;
}[];
export type MediaType = PicturePngJpg | YoutubeVideo;
/**
 * Picture (png / jpg)
 */
export type PicturePngJpg = "picture";
/**
 * Youtube video
 */
export type YoutubeVideo = "youtube";
export type Type5 =
    | ProductMediaPicture
    | BrandItemBackgroundPicture3200X1900Ratioed
    | ItemBackgroundPicture3000X3000Ratioed
    | CertificateBackgroundPicture1900X3200TBDPreferablyDarkWithLogoOnTop;
/**
 * Product media / picture
 */
export type ProductMediaPicture = "product";
/**
 * Brand Item Background Picture (3200x1900) ratioed
 */
export type BrandItemBackgroundPicture3200X1900Ratioed = "brandItemBackgroundPicture";
/**
 * Item Background Picture (3000x3000) ratioed
 */
export type ItemBackgroundPicture3000X3000Ratioed = "itemBackgroundPicture";
/**
 * Certificate Background Picture (1900x3200 TBD) preferably dark - with logo on top
 */
export type CertificateBackgroundPicture1900X3200TBDPreferablyDarkWithLogoOnTop = "certificateBackgroundPicture";
export type URL = string;
export type MediaHash = string;
export type MediaOrderNumber = number;
/**
 * List of Medias (picture, video, ...)
 */
export type Medias = {
    mediaType?: MediaType;
    type?: Type5;
    url?: URL;
    hash?: MediaHash;
    order?: MediaOrderNumber;
    [k: string]: any;
}[];
export type Type6 = Color | Material | Printed;
/**
 * Color
 */
export type Color = "color";
/**
 * Material
 */
export type Material = "material";
/**
 * Printed
 */
export type Printed = "printed";
export type Value1 = string;
export type Attributes = {
    type?: Type6;
    value?: Value1;
    [k: string]: any;
}[];
export type Material1 = Cashmere | Cotton | DenimJeans;
/**
 * Cashmere
 */
export type Cashmere = "cashmere";
/**
 * Cotton
 */
export type Cotton = "cotton";
/**
 * Denim - Jeans
 */
export type DenimJeans = "denim-jeans";
export type Value2 = string;
/**
 * Pourcentage without % (numeric)
 */
export type Pourcentage = string;
export type Materials = {
    material?: Material1;
    value?: Value2;
    pourcentage?: Pourcentage;
    [k: string]: any;
}[];
export type Type7 = Height | Width | Depth | Size;
/**
 * Height
 */
export type Height = "height";
/**
 * Width
 */
export type Width = "width";
/**
 * Depth
 */
export type Depth = "depth";
/**
 * Size
 */
export type Size = "depth";
export type Value3 = string;
export type Unit = Inch | Centimer | EU | UK | US;
/**
 * Inch
 */
export type Inch = "in";
/**
 * Centimer
 */
export type Centimer = "cm";
/**
 * EU
 */
export type EU = "eu";
/**
 * UK
 */
export type UK = "uk";
/**
 * US
 */
export type US = "us";
export type Sizes = {
    type?: Type7;
    value?: Value3;
    unit?: Unit;
    [k: string]: any;
}[];
/**
 * Country of manufacture in final assembly stage. (ISO 3166 alpha-3)
 */
export type CountryManufacturing = string;
/**
 * Facility Identification in Open Apparel Registry (OAR) or GS1 database
 */
export type FacilityIdentificationNumber = string;
export type Name1 = FairTrade | WWF;
/**
 * Fair Trade
 */
export type FairTrade = "fairtrade";
/**
 * WWF
 */
export type WWF = "wwf";
/**
 * List any certifications that the product has received.
 */
export type ProductCertificationsCompliance = {
    name?: Name1;
    [k: string]: any;
}[];

export interface ArianeeCertificatei18n {
    $schema: $Schema;
    name?: Name;
    sku?: SKU;
    gtin?: GTIN;
    brandInternalId?: BrandInternalID;
    category?: Category;
    subCategory?: SubCategory;
    intended?: Intended;
    serialnumber?: SerialNumber1;
    subBrand?: SubBrand;
    model?: Model;
    language?: Language;
    description?: Description;
    subDescription?: DescriptionMore;
    externalContents?: ExternalContents;
    i18n?: OtherLanguagesDescriptionExternalContents;
    msrp?: ManufacturersSuggestedRetailPrice;
    medias?: Medias;
    attributes?: Attributes;
    materials?: Materials;
    size?: Sizes;
    manufacturingCountry?: CountryManufacturing;
    facilityId?: FacilityIdentificationNumber;
    productCertification?: ProductCertificationsCompliance;
    [k: string]: any;
}
