/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type $Schema = string;
export type Name = string;
export type Version = string;
export type Type = "serialnumber" | "casenumber" | "movementnumber";
export type Value = string;
export type SerialNumber = {
    type?: Type;
    value?: Value;
    [k: string]: any;
}[];
export type Brand = string;
export type Model = string;
export type Description = string;
export type Type1 = string;
/**
 * url
 */
export type BrandLogoHeader = string;
/**
 * url
 */
export type MainPicture = string;
/**
 * url
 */
export type PictureURL = string;
export type Pictures = {
    src?: PictureURL;
    [k: string]: any;
}[];
export type Type2 = "color" | "material" | "printed";
export type Value1 = string;
export type Attributes = {
    type?: Type2;
    value?: Value1;
    [k: string]: any;
}[];
export type Type3 = "height" | "width" | "depth" | "depth";
export type Value2 = string;
export type Unit = "in" | "cm" | "eu" | "uk" | "us";
export type Sizes = {
    type?: Type3;
    value?: Value2;
    unit?: Unit;
    [k: string]: any;
}[];
/**
 * Facebook Page Id
 */
export type Facebook = string;
/**
 * account
 */
export type Instagram = string;
/**
 * account
 */
export type Twitter = string;
export type Title = string;
export type Url = string;
export type BackgroundColor = string;
export type Color = string;
/**
 * Icon
 */
export type Icon = string;
export type ExternalContents = {
    title?: Title;
    url?: Url;
    backgroundColor?: BackgroundColor;
    color?: Color;
    icon?: Icon;
    [k: string]: any;
}[];
/**
 * Json URL to surcharge this certificate overtime
 */
export type JsonSurcharger = string;

export interface ArianeeCertificate {
    $schema: $Schema;
    name?: Name;
    v?: Version;
    serialnumber?: SerialNumber;
    brand?: Brand;
    model?: Model;
    description?: Description;
    type?: Type1;
    brandLogoHeader?: BrandLogoHeader;
    picture?: MainPicture;
    pictures?: Pictures;
    attributes?: Attributes;
    size?: Sizes;
    socialmedia?: SocialMedia;
    externalContents?: ExternalContents;
    jsonSurcharger?: JsonSurcharger;
    [k: string]: any;
}
export interface SocialMedia {
    facebook?: Facebook;
    instagram?: Instagram;
    twitter?: Twitter;
    [k: string]: any;
}
