# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5.1
  gh: circleci/github-cli@2.1.0

jobs:
  build-and-test-uat:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Fix up git URLs
          command: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
      - run:
          name: Declare domain blockchain
          command: echo 127.0.0.1 blockchain | sudo tee -a /etc/hosts
      - run:
          name: Declare domain wallet
          command: echo 127.0.0.1 wallet | sudo tee -a /etc/hosts
      - node/install-packages
      - run:
          name: Launch docker
          command: docker-compose up --build --detach --force-recreate
      - run:
          name: Run tests
          command: npm test
  build-and-test-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run:
          name: Install python
          command: |
            apt-get update -y
            apt-get install -y python3.8 python3-pip
      - node/install-packages
      - run:
          name: Fix up git URLs
          command: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
      - run:
          name: Build wallet
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:playwright
      - persist_to_workspace:
          root: ./
          paths:
            - "*"

  deploy-npm: 
    docker: 
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - node/install-packages
      - run: 
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish --ignore-scripts

  bump-version-github:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "66:05:66:0b:67:7a:59:b2:25:4b:88:f9:97:50:c4:88"
      - run:
          name: Config Github account
          command: |
            git config user.name "Package Version Bot"
            git config user.email "tech@arianee.org"
      - run:
          name: Change version in package.json
          command: npm run bump:minor

  push-gh-release:
      docker:
          - image: cimg/node:16.14.2
      steps:
          - checkout
          - gh/setup:
              version: 2.14.3
              token: GITHUBTOKEN
          - run:
              command: 'gh release create v$(grep ''"version": "'' package.json | cut -d ''"'' -f4) --generate-notes'
              name: Create Github Release

workflows:
  sample:
    jobs:
      - build-and-test-uat
      - build-and-test-playwright
      - deploy-approval:
          type: approval
          requires:
            - build-and-test-uat
            - build-and-test-playwright
          filters:
            branches:
              only:
                - master
      - deploy-npm:
          requires:
            - deploy-approval
      - push-gh-release:
          requires:
            - deploy-npm
      - bump-version-github:
          requires:
            - deploy-npm
