/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type $Schema = string;
export type Name = string;
export type Website = string;
export type MotherCompany = string;
export type CertificateURI = string;
export type ArianeeMember = boolean;
export type StreetAddress = string;
export type ZipCode = string;
export type City = string;
export type State = string;
export type Country = string;
export type Name1 = string;
export type Email = string;
export type Title = string;
export type Contacts1 = Contacts[];
/**
 * url
 */
export type BrandLogoHeader = string;
/**
 * url
 */
export type BrandLogoSquare = string;
export type InAppHTML = string;
/**
 * Facebook Page Id
 */
export type Facebook = string;
/**
 * account
 */
export type Instagram = string;
/**
 * account
 */
export type Twitter = string;
export type Title1 = string;
export type Url = string;
export type BackgroundColor = string;
export type Color = string;
/**
 * URL
 */
export type Icon = string;
export type ExternalContents1 = ExternalContents[];

export interface ArianeeIdentity {
    $schema: $Schema;
    name?: Name;
    website?: Website;
    mother_company?: MotherCompany;
    certificate_uri?: CertificateURI;
    arianee_member?: ArianeeMember;
    address?: Address;
    contacts?: Contacts1;
    brandLogoHeader?: BrandLogoHeader;
    brandLogoSquare?: BrandLogoSquare;
    inAppHTML?: InAppHTML;
    socialmedia?: SocialMedia;
    externalContents?: ExternalContents1;
    [k: string]: any;
}
export interface Address {
    street_address: StreetAddress;
    zipcode: ZipCode;
    city: City;
    state: State;
    country: Country;
    [k: string]: any;
}
export interface Contacts {
    name?: Name1;
    email?: Email;
    title?: Title;
    [k: string]: any;
}
export interface SocialMedia {
    facebook?: Facebook;
    instagram?: Instagram;
    twitter?: Twitter;
    [k: string]: any;
}
export interface ExternalContents {
    title?: Title1;
    url?: Url;
    backgroundColor?: BackgroundColor;
    color?: Color;
    icon?: Icon;
    [k: string]: any;
}
