/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type $Schema = string;
/**
 * Name of the brand
 */
export type BrandName = string;
/**
 * Name of the company
 */
export type CompanyName = string;
/**
 * Name of parent company
 */
export type ParentCompanyName = string;
/**
 * Brand / Company description in HTML (main language)
 */
export type Description = string;
export type Type = WebsiteMain | Eshop | Other;
/**
 * Website (main)
 */
export type WebsiteMain = 'website';
/**
 * Eshop
 */
export type Eshop = 'eshop';
/**
 * other
 */
export type Other = 'other';
export type Title = string;
export type Url = string;
export type OrderNumber = number;
/**
 * List of External Contents such as website / documentation
 */
export type ExternalContents1 = ExternalContents[];
export type Language = French | EnglishAmerican | TraditionalChinese | SimplifiedChinese;
/**
 * French
 */
export type French = 'fr-FR';
/**
 * English (american)
 */
export type EnglishAmerican = 'en-US';
/**
 * Traditional chinese
 */
export type TraditionalChinese = 'zh-TW';
/**
 * Simplified chinese
 */
export type SimplifiedChinese = 'zh-CN';
export type Description1 = string;
export type Type1 = WebsiteMain1 | Eshop1 | Other1;
/**
 * Website (main)
 */
export type WebsiteMain1 = 'website';
/**
 * Eshop
 */
export type Eshop1 = 'eshop';
/**
 * other
 */
export type Other1 = 'other';
export type Title1 = string;
export type Url1 = string;
/**
 * List of External Contents such as website / documentation
 */
export type ExternalContents3 = ExternalContents2[];
/**
 * Brand / Company description in HTML & external contents (specific language)
 */
export type OtherLanguagesDescriptionExternalContents = {
    language?: Language;
    description?: Description1;
    externalContents?: ExternalContents3;
    [k: string]: any;
}[];
/**
 * Company is part of Arianee Association
 */
export type ArianeeMember = NotMember | AssociateMember | GroupMember | MaisonMember;
/**
 * Not member
 */
export type NotMember = 'not_member';
/**
 * Associate Member
 */
export type AssociateMember = 'associate_member';
/**
 * Group member
 */
export type GroupMember = 'group_member';
/**
 * Maison member
 */
export type MaisonMember = 'maison_member';
export type StreetAddress = string;
export type StreetAddress2 = string;
export type ZipCode = string;
export type City = string;
export type State = string;
export type Country = string;
export type Name = string;
export type Email = string;
export type Title2 = string;
export type Type2 = Support | Sales | Headquarter | Other2;
/**
 * Support
 */
export type Support = 'support';
/**
 * Sales
 */
export type Sales = 'sales';
/**
 * Headquarter
 */
export type Headquarter = 'hq';
/**
 * other
 */
export type Other2 = 'other';
/**
 * List of company contacts
 */
export type Contacts1 = Contacts[];
export type Type3 =
    | BrandLogoHeader2000X700TransparentWorkingWithAWhiteBackgroundPNG
    | BrandLogoHeader2000X700TransparentWorkingWithABlackBackgroundPNG
    | BrandLogoSquare1000X1000NoTransparency
    | BrandCollectionPicture3200X1900Ratioed
    | BrandItemBackgroundPicture3200X1900Ratioed
    | ItemBackgroundPicture3000X3000Ratioed
    | BrandBackgroundPicture1900X3200PreferablyDark
    | CertificateBackgroundPicture1900X3200TBDPreferablyDarkWithLogoOnTop;
/**
 * Brand Logo Header (2000x700) transparent (working with a white background) PNG
 */
export type BrandLogoHeader2000X700TransparentWorkingWithAWhiteBackgroundPNG = 'brandLogoHeader';
/**
 * Brand Logo Header (2000x700) transparent (working with a black background) PNG
 */
export type BrandLogoHeader2000X700TransparentWorkingWithABlackBackgroundPNG = 'brandLogoHeaderReversed';
/**
 * Brand Logo Square (1000x1000) no transparency
 */
export type BrandLogoSquare1000X1000NoTransparency = 'brandLogoSquare';
/**
 * Brand Collection Picture (3200x1900) ratioed
 */
export type BrandCollectionPicture3200X1900Ratioed = 'brandHomePicture';
/**
 * Brand Item Background Picture (3200x1900) ratioed
 */
export type BrandItemBackgroundPicture3200X1900Ratioed = 'brandItemBackgroundPicture';
/**
 * Item Background Picture (3000x3000) ratioed
 */
export type ItemBackgroundPicture3000X3000Ratioed = 'itemBackgroundPicture';
/**
 * Brand Background picture (1900x3200) preferably dark
 */
export type BrandBackgroundPicture1900X3200PreferablyDark = 'brandBackgroundPicture';
/**
 * Certificate Background Picture (1900x3200 TBD) preferably dark - with logo on top
 */
export type CertificateBackgroundPicture1900X3200TBDPreferablyDarkWithLogoOnTop = 'certificateBackgroundPicture';
export type URL = string;
export type ImageHash = string;
/**
 * List of Pictures
 */
export type Pictures = {
    type?: Type3;
    url?: URL;
    hash?: ImageHash;
    [k: string]: any;
}[];
export type Type4 = Facebook | Instagram | Twitter | Youtube;
/**
 * Facebook
 */
export type Facebook = 'facebook';
/**
 * Instagram
 */
export type Instagram = 'instagram';
/**
 * Twitter
 */
export type Twitter = 'twitter';
/**
 * Youtube
 */
export type Youtube = 'youtube';
export type Value = string;
/**
 * List of Social Media
 */
export type SocialMedia = {
    type?: Type4;
    value?: Value;
    [k: string]: any;
}[];
/**
 * Certificate Management Platform RPC URL
 */
export type RPCEndpoint = string;

/**
 * Describing an Arianee Brand Identity.
 */
export interface ArianeeBrandIdentityi18n {
    $schema: $Schema;
    name?: BrandName;
    companyName?: CompanyName;
    parentCompanyName?: ParentCompanyName;
    description?: Description;
    externalContents?: ExternalContents1;
    i18n?: OtherLanguagesDescriptionExternalContents;
    arianeeMembership?: ArianeeMember;
    address?: Address;
    contacts?: Contacts1;
    pictures?: Pictures;
    socialmedia?: SocialMedia;
    rpcEndpoint?: RPCEndpoint;
    [k: string]: any;
}
export interface ExternalContents {
    type?: Type;
    title?: Title;
    url?: Url;
    order?: OrderNumber;
    [k: string]: any;
}
export interface ExternalContents2 {
    type?: Type1;
    title?: Title1;
    url?: Url1;
    [k: string]: any;
}
/**
 * Company HQ address
 */
export interface Address {
    street_address?: StreetAddress;
    street_address2?: StreetAddress2;
    zipcode?: ZipCode;
    city?: City;
    state?: State;
    country?: Country;
    [k: string]: any;
}
export interface Contacts {
    name?: Name;
    email?: Email;
    title?: Title2;
    type?: Type2;
    [k: string]: any;
}
